### ISSUE TITLE
LLVM 11 builds are not added to the workflow

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#19]
Due to name collisions, LLVM 11 builds are not added to the matrix. Current solution:

```diff
git dh generate_workflow.py
diff --git a/generate_workflow.py b/generate_workflow.py
index 7898942..26787fb 100755
--- a/generate_workflow.py
+++ b/generate_workflow.py
@@ -29,7 +29,7 @@ def get_repo_ref(config, tree_name):
 def get_job_name(build):
     return "ARCH=" + (build["ARCH"] if "ARCH" in build else "x86_64") \
     + " LLVM=" + str(int(build["llvm"])) + " LLVM_IAS=" + str(int(build["llvm_ias"])) \
-    + " BOOT=" + str(int(build["boot"]))
+    + " BOOT=" + str(int(build["boot"])) + " LLVM " + str(int(build["llvm_version"]))


 def sanitize_job_name(name):
```

which will generate something like

```
  ARCH_arm_LLVM_1_LLVM_IAS_1_BOOT_1_LLVM_11_multi_v5_defconfig:
    runs-on: ubuntu-20.04
    needs: kick_tuxbuild
    name: ARCH=arm LLVM=1 LLVM_IAS=1 BOOT=1 LLVM 11
```

and

```
  ARCH_arm_LLVM_1_LLVM_IAS_1_BOOT_1_LLVM_12_multi_v5_defconfig:
    runs-on: ubuntu-20.04
    needs: kick_tuxbuild
    name: ARCH=arm LLVM=1 LLVM_IAS=1 BOOT=1 LLVM 12
```

although @nickdesaulniers had talked about just making the job values a UUID because they do not show up in GitHub's UI (only the `name:` value does).
